spring:
  # h2 콘솔 사용
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # JPA Settings
  # ddl-auto : create, create-drop, validate, update, none
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
    database-platform: H2

logging.level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace